### ISSUE TITLE
Duplicate entries (objects) for sensor value in SVG

### ISSUE THREAD

**Issue by nmacia** [nmacia/Termites#1]
<text transform="matrix(1 0 0 1 650.8848 604.6475)" font-family="Amatic SC" font-size="24">-00.0°C</text>
<text transform="matrix(1 0 0 1 650.8848 604.6475)" fill="none" stroke="#FFFFFF" stroke-miterlimit="10" font-family="Amatic SC" font-size="24">-00.0°C</text>

**Comment by nmacia** [comment]
`<text transform="matrix(1 0 0 1 650.8848 604.6475)" font-family="Amatic SC" font-size="24">-00.0°C</text>`

`<text transform="matrix(1 0 0 1 650.8848 604.6475)" fill="none" stroke="#FFFFFF" stroke-miterlimit="10" font-family="Amatic SC" font-size="24">-00.0°C</text>`

**Comment by ladevis** [comment]
duplicates fixed and id solved
