### ISSUE TITLE
Fix drag and drop

### ISSUE THREAD

**Issue by ladevis** [nmacia/Termites#15]
<img width="610" alt="screen shot 2017-08-04 at 5 52 22 pm" src="https://user-images.githubusercontent.com/9956093/28976329-bac3e84e-793d-11e7-92d5-b162efb07f07.png">
remove Embedded div in the main framework.

`/* Drag and drop relate sensors emotions */

function allowDrop(ev) {
    ev.preventDefault();
}

function drag(ev) {
  var draggableParentDiv = $(ev.target).closest('.r-button-sensor');
    ev.dataTransfer.setData("text", draggableParentDiv[0].id);
}

function drop(ev) {
    ev.preventDefault();
    var data = ev.dataTransfer.getData("text");
    ev.target.appendChild(document.getElementById(data));
}

`

**Comment by ladevis** [comment]
@nmacia 
`/* Drag and drop relate sensors emotions */

function allowDrop(ev) {
    ev.preventDefault();
}

var fromId = {};

function drag(ev) {
  var draggableButtonDiv = $(ev.target).closest('.r-button-sensor')[0];
  
  var containerOfButton = draggableButtonDiv.parentElement;
  if (containerOfButton.id !== 'center-dragbox-forsensors') {
    fromId[draggableButtonDiv.id] = containerOfButton.id;
      
  }
    ev.dataTransfer.setData("draggedId", draggableButtonDiv.id); 
    
    console.log("containerOfButton.id: " + containerOfButton.id);  
}

function drop(ev) {
    ev.preventDefault();
    var draggedId = ev.dataTransfer.getData("draggedId");
    
    console.log(fromId);
    if (event.target.id !== "center-dragbox-forsensors") {
      $("#" + fromId[draggedId]).append(document.getElementById(draggedId));
    }
    else {
      $('#center-dragbox-forsensors').append(document.getElementById(draggedId));
  
    }
  
   
}`

**Comment by nmacia** [comment]
event was not defined
`if (event.target.id !== "center-dragbox-forsensors") {`

`if (ev.target.id !== "center-dragbox-forsensors") {`
