### ISSUE TITLE
generate groups style and logic

### ISSUE THREAD

**Issue by ladevis** [nmacia/Termites#16]
<img width="362" alt="screen shot 2017-08-04 at 5 56 18 pm" src="https://user-images.githubusercontent.com/9956093/28976464-499a608e-793e-11e7-975f-0ad15dcb13d9.png">

**Comment by ladevis** [comment]
- [x] Graphics css
  - Rows
  - Titles
  - Responsiveness


- [x] Logic from the drag and drop to the groups

- [x] Icon placement geometry inside of the groups

**Comment by nmacia** [comment]
Icons are places in a circle shape following the example at https://codepen.io/HugoGiraudel/pen/vEJXGm 
Adjust size by changing properties of .circle-container > *
