### ISSUE TITLE
Format ID in SVG

### ISSUE THREAD

**Issue by nmacia** [nmacia/Termites#2]
`<g id="temp-3">`
`<text id="temp-3-value" transform="matrix(1 0 0 1 406.4927 754.7295)" stroke="#FFFFFF" font-size="24">-00.0°C</text>`
`</g>`

The SVG requires an id inside the object text to be able to change it through js.
Format rules:
1. Main ID: [first three (or four) letters of sensor type]-[sensor id]
2. Text ID: [first three (or four) letters of sensor type]-[sensor id]-value

**Comment by ladevis** [comment]
In date.js you will find // Catalog of sensors installed and their IDs in the SVG. with all the properties and id per each type of sensor.
## Generic function for the values of the sensors
Not a good idea. Values are very different. The graphic design is very different. Soon we will need to invert the values or do some maths with them.
 It would be better to have a function per each type of sensor.
## Height and width
I would like to be able to automatically change the width and the height of the svg file from px values to 100%.
Normally I change it manually but this is not really sustainable.
```
<svg version="1.1" id="Livello_1" xmlns:x="&ns_extend;" xmlns:i="&ns_ai;" xmlns:graph="&ns_graphs;"
	 xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="**100%**"
	 height="**100%**" viewBox="115.293 -467.866 1041.811 801" enable-background="new 115.293 -467.866 1041.811 801"
	 xml:space="preserve">
```
## Font
I would like to change the font family automatically to Amatic SC and linked to google fonts.
## Presence and ghost:
In the svg you will find two images that should change according to the values (0 or 1)

![presence](https://cloud.githubusercontent.com/assets/9956093/25894532/749829f2-357c-11e7-8179-655d68401237.png)
![presence-inv](https://cloud.githubusercontent.com/assets/9956093/25894533/74992d8e-357c-11e7-9583-90c8f7bf7063.png)
