### ISSUE TITLE
navigation bar mobile background or position

### ISSUE THREAD

**Issue by ladevis** [nmacia/Termites#23]
<img width="401" alt="screen shot 2017-08-07 at 6 02 53 pm" src="https://user-images.githubusercontent.com/9956093/29035078-b4546e16-7b9a-11e7-8727-788fbf6dc872.png">

**Comment by nmacia** [comment]
https://github.com/nmacia/Termites/commit/04ea050846e98e7339e6950ee1acad12c5a5b337
![image](https://user-images.githubusercontent.com/5067678/29044621-419a302e-7b8e-11e7-8db7-f81aadb0eb6c.png)
