### ISSUE TITLE
Last Activation date time

### ISSUE THREAD

**Issue by ladevis** [nmacia/Termites#5]
***Print the date/time of last activation under sensor value** 
Temperature and Light are already implemented in the svg
There is a font weight issue that I have to solve ('font-weight', '500')
***Highlight the sensors that have not responded within certain frame with a red color** 
(Maybe we can find another graphic representation, not red color)

**Comment by ladevis** [comment]
*Print the date/time of last activation under sensor value
Fixed

**Comment by ladevis** [comment]
*Highlight the sensors that have not responded warning sign. 
generic id ends with -warning
@jpnawyn if the sensor does not respond within a certain timeout setAttribute("display","block")

**Comment by ladevis** [comment]
@jpnawyn convert last activation time to Andorra time zone

**Comment by ladevis** [comment]
@jpnawyn if the sensor does not respond within a certain timeout -warning
`svgDoc.getElementById(sensorIDs[0].id[i]+'-warning').setAttribute("class","sshow")`
.setAttribute("class","sshow") (Display warning)
.setAttribute("class", "st0") (Hide warning)

Typical `id="ATP076-temperature-warning"` (Name of the sensor, type, warning)
temperature: temperature
light: light
humidity: humidity
presence: presence
proximity: proximity
pressure: pressure
co2: co2

**Comment by ladevis** [comment]
Example Phantom:
`<g id="sensor-presence-ATP074" class="st1">
				    <g id="ATP074-presence-icon-1">
					<image style="overflow:visible;enable-background:new    ;" width="131" height="150"  xlink:href="../img/sensors/presence-inv.png"  transform="matrix(0.6667 0 0 0.6667 205.2949 499.6975)">
				    </image>
                    </g>
				    <g id="ATP074-presence-icon-0" class="st0">
					<image style="overflow:visible;enable-background:new    ;" width="131" height="150" xlink:href="../img/sensors/presence.png"  transform="matrix(0.5 0 0 0.5 223.1281 524.6953)">
				    </image>
                    </g>
				    <rect x="283.4" y="559.5" class="st8" width="25" height="28"/>
				    <text id="ATP074-sensor-presence-value" transform="matrix(1 0 0 1 283.4022 583.2733)" class="st3 st9">?</text>
                    <g id="ATP074-presence-warning" class="st0">
                      <image style="overflow:visible;enable-background:new    ;" width="173" height="150" xlink:href="../img/sensors/warning-sign.png"  transform="matrix(0.15 0 0 0.15 210 583.2733)">
                      </image>
                    </g>
			</g>`

**Comment by ladevis** [comment]
84bbba0 Updated all classrooms ids :)
@jpnawyn

**Comment by jpnawyn** [comment]
All issues herein resolved.
